title: "BioComp - język do biocomputingu - dsl.biokomputery.pl"
description: "Specyfikacja, wykorzystanie, przykłady graficzne logiki i symulacji z wykorzystaniem BioComp języka domenowo-specyficznego (DSL) do edukacji i wdrażania biocomputingu obejmuje elementy języka opisu eksperymentów, symulacji, designu i utrzymania systemów biokomputerowych."
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"  
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
